
site_name: 510 EspoCRM training
site_url: https://rodekruis.github.io/espocrm-training/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - toc:
        permalink : true
        permalink_title: Specific link to this section
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - privacy
  - search
  - glightbox

theme:
    name: material
    language: en
    palette:
      primary: custom
    logo: assets/img/510Logo.png
    favicon: /assets/img/favicon.ico
    features:
      - navigation.top
      - navigation.instant
      - navigation.instant.progress

extra:
  generator: false
#   alternate:
#     - name: English
#       link: /
#       lang: en
#     - name: Nederlands
#       link: /nl/
#       lang: nl

nav:
    - 'Home': 'index.md'
    - 'Hosting':
      - 'Hosting options': 'hosting/page1.md' 
    - 'General': 
      - 'Log in': 'general/page1.md'
      - 'Change password': 'general/page2.md'
      - 'Change language': 'general/page3.md'
      - 'Add users': 'general/page4.md'
      - 'Roles and permissions': 'general/page5.md'
    - 'PAM':
      - 'Persons Affected': 'pam/page1.md'
      - 'Households': 'pam/page2.md'
      - 'Programs': 'pam/page3.md'
      - 'Tasks': 'pam/page4.md'
      - 'Volunteers': 'pam/page5.md'
      - 'Data import with Excel': 'pam/page6.md'
      - 'Registration with Kobo': 'pam/page7.md'
    - 'Rental Accommodation' :
      - 'Affected Households': 'rental/page1.md'
      - 'Accommodations': 'rental/page2.md'
      - 'Matches': 'rental/page3.md'
      - 'Cash distributions': 'rental/page4.md'
      - 'Transfers': 'rental/page5.md'
      - 'Message Templates': 'rental/page6.md'
      - 'Messages': 'rental/page7.md'
      - 'Data import with Excel': 'rental/page8.md'
      - 'Registration with Kobo': 'rental/page9.md'
    - '121 Payment platform' :
      - '121 platform for making payments': 'payment/page1.md'
    - 'Customization': 
      - 'How to create a new entity': 'customization/page1.md'
      - 'How to link entities': 'customization/page2.md'
      - 'Sending SMS messages': 'customization/page3.md'
      - 'Mass messaging with WhatsApp/Twilio': 'customization/page4.md'
      - 'DEH': 'customization/page5.md'
      - 'Sending emails': 'customization/page6.md'
      - 'Integration of EspoCRM with KoboToolbox ': 'customization/page7.md'
      - 'Integration of EspoCRM with Twilio': 'customization/page8.md'
      - 'Creating dashboards in EspoCRM': 'customization/page10.md'
      - 'Flowcharts': 'customization/page11.md'
    - 'Advanced Pack':
      - 'Advanced Pack License': 'advanced/page1.md'
    - 'Data protection': 
      - 'GDPR compliance': 'protection/page1.md'
      - 'Version control': 'protection/page3.md'
      - 'Best practices': 'protection/page4.md'
    
